server:
  port: ${PORT_LAUNCH:8080}
  servlet:
    context-path: /api

frontend:
  url: ${FRONTEND_URL:http://localhost:${server.port}${server.servlet.context-path}}
  change-password-path: /auth/changePassword
  confirm-registration-path: /auth/confirm-registration

spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/code-busters-db?serverTimezone=UTC}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:root}
    dbcp2:
      max-wait-millis: 30000
      validation-query: /* ping */ select 1
      validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: ${PARAM_DDL_AUTO:create}
    show-sql: ${PARAM_SHOW_SQL:true}
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  docker:
    compose:
      lifecycle-management: start-only
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR


jwt:
  secret: ${JWT_SECRET:MI_SUPER_SECRETO_ULTRA_SEGURO_12345678901234567890_ULTRA_SEGURO_MI_SUPER_SECRETOULTRA_SEGURO_MI_SUPER_SECRETO_1234567890}

springdoc:
  swagger-ui:
    tagsSorter: alpha
